# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inventory_pb2 as inventory__pb2


class InventoryOptimizationStub(object):
    """Definição do Serviço
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OptimizeInventory = channel.unary_unary(
                '/inventory.InventoryOptimization/OptimizeInventory',
                request_serializer=inventory__pb2.InventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryResponse.FromString,
                )
        self.StreamOptimizeInventory = channel.unary_stream(
                '/inventory.InventoryOptimization/StreamOptimizeInventory',
                request_serializer=inventory__pb2.BulkInventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryResponse.FromString,
                )


class InventoryOptimizationServicer(object):
    """Definição do Serviço
    """

    def OptimizeInventory(self, request, context):
        """Um RPC (Remote Procedure Call) simples
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOptimizeInventory(self, request, context):
        """Server Streaming RPC 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryOptimizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OptimizeInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeInventory,
                    request_deserializer=inventory__pb2.InventoryRequest.FromString,
                    response_serializer=inventory__pb2.InventoryResponse.SerializeToString,
            ),
            'StreamOptimizeInventory': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOptimizeInventory,
                    request_deserializer=inventory__pb2.BulkInventoryRequest.FromString,
                    response_serializer=inventory__pb2.InventoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryOptimization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryOptimization(object):
    """Definição do Serviço
    """

    @staticmethod
    def OptimizeInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryOptimization/OptimizeInventory',
            inventory__pb2.InventoryRequest.SerializeToString,
            inventory__pb2.InventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamOptimizeInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/inventory.InventoryOptimization/StreamOptimizeInventory',
            inventory__pb2.BulkInventoryRequest.SerializeToString,
            inventory__pb2.InventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
