# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\xcf\x01\n\x10InventoryRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x15\n\rcurrent_stock\x18\x02 \x01(\x05\x12\x18\n\x10predicted_demand\x18\x03 \x01(\x05\x12\x15\n\rreorder_level\x18\x04 \x01(\x05\x12\x19\n\x0csafety_stock\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x1f\n\x12supplier_lead_time\x18\x06 \x01(\x05H\x01\x88\x01\x01\x42\x0f\n\r_safety_stockB\x15\n\x13_supplier_lead_time\"\x7f\n\x11InventoryResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x18\n\x10reorder_quantity\x18\x02 \x01(\x05\x12*\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x1a.inventory.InventoryAction\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t*K\n\x0fInventoryAction\x12\r\n\tNO_ACTION\x10\x00\x12\x0c\n\x08SCALE_UP\x10\x01\x12\x0e\n\nSCALE_DOWN\x10\x02\x12\x0b\n\x07REORDER\x10\x03\x32g\n\x15InventoryOptimization\x12N\n\x11OptimizeInventory\x12\x1b.inventory.InventoryRequest\x1a\x1c.inventory.InventoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVENTORYACTION']._serialized_start=369
  _globals['_INVENTORYACTION']._serialized_end=444
  _globals['_INVENTORYREQUEST']._serialized_start=31
  _globals['_INVENTORYREQUEST']._serialized_end=238
  _globals['_INVENTORYRESPONSE']._serialized_start=240
  _globals['_INVENTORYRESPONSE']._serialized_end=367
  _globals['_INVENTORYOPTIMIZATION']._serialized_start=446
  _globals['_INVENTORYOPTIMIZATION']._serialized_end=549
# @@protoc_insertion_point(module_scope)
